### ISSUE TITLE
"Value objects"

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/args#1]
These are called value objects.

Please see mine
https://github.com/szepeviktor/phpstan-wordpress/tree/master/example
`class*.php`

**Comment by johnbillion** [comment]
It crossed my mind that these look a bit like VO _containers_, except I haven't yet implemented any VOs for those properties that can be represented in a manner more complex than a primitive type (eg `meta_query`). They're not quite VOs because the container isn't immutable due to the recommended method for instantiating the class before populating its properties in order to benefit from editor intellisense.

Did you manually create those classes in phpstan-wordpress?

**Comment by szepeviktor** [comment]
> Did you manually create those classes in phpstan-wordpress?

Oh yes.

**Comment by szepeviktor** [comment]
From the README

> I'll be working on a partly automated process for creating these at some point.

So you are interested in an automated conversion.
